# nn parameters
INPUT_NUM = 8
OUTPUT_NUM = 4

NORMAL_NUM_UPPER_LIMIT = 10
NORMAL_NUM_LOWER_LIMIT = 4

MODULATION_NUM_UPPER_LIMIT = 10
MODULATION_NUM_LOWER_LIMIT = 1

CONNECTION_NUM_UPPER_LIMIT = 20
CONNECTION_NUM_LOWER_LIMIT = 10

WEIGHT_UPPER_LIMIT = 1.0
WEIGHT_LOWER_LIMIT = -1.0

BIAS_UPPER_LIMIT = 1.0
BIAS_LOWER_LIMIT = -1.0


