# nn parameters
INPUT_NUM = 5
OUTPUT_NUM = 2

NORMAL_NUM_UPPER_LIMIT = 5
NORMAL_NUM_LOWER_LIMIT = 1

MODULATION_NUM_UPPER_LIMIT = 5
MODULATION_NUM_LOWER_LIMIT = 0

NEURON_NUM_UPPER_LIMIT = 8

CONNECTION_NUM_UPPER_LIMIT = 10
CONNECTION_NUM_LOWER_LIMIT = 5

WEIGHT_UPPER_LIMIT = 1.0
WEIGHT_LOWER_LIMIT = -1.0

BIAS_UPPER_LIMIT = 1.0
BIAS_LOWER_LIMIT = -1.0

EVOLUTION_PARAM_UPPER_LIMIT = 1.0
EVOLUTION_PARAM_LOWER_LIMIT = -1.0

AGENT_NUM = 10

EPSIRON = 0.1
