# nn parameters
INPUT_NUM = 2
OUTPUT_NUM = 2

NORMAL_NUM_UPPER_LIMIT = 10
NORMAL_NUM_LOWER_LIMIT = 2

MODULATION_NUM_UPPER_LIMIT = 10
MODULATION_NUM_LOWER_LIMIT = 2

CONNECTION_NUM_UPPER_LIMIT = 10
CONNECTION_NUM_LOWER_LIMIT = 8

WEIGHT_UPPER_LIMIT = 1.0
WEIGHT_LOWER_LIMIT = -1.0

BIAS_UPPER_LIMIT = 1.0
BIAS_LOWER_LIMIT = -1.0


